### ISSUE TITLE
!bots command not working on main bot

### ISSUE THREAD

**Issue by Sandraa01** [vcodes-xyz/vcodes#32]
I am getting an error like this when I do !bots command!
![Screenshot_2021-08-05-01-21-27-970_com android chrome](https://user-images.githubusercontent.com/73333746/128245911-dad4a441-1275-407f-8b6c-ba59d2decd4a.jpg)
![Uploading Screenshot_2021-08-05-01-21-23-519_com.android.chrome.jpg…]()

**Comment by iClaudette** [comment]
We answered this question on Discord, please join our server and go to the message from the message link below.

Discord: https://discord.gg/z7dBzygse4
Message: https://discord.com/channels/796048327024050176/824326276034723890/872594567361359932
